/**
 * Activity catalog — the single source of truth for all ~50 sales
 * activities/offers an AE can run.  Each activity carries ordered AE
 * steps, target segment guidance, expected outcomes, and timing.
 *
 * Activities are grouped into categories for UI display.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ActivityChannel =
  | 'email'
  | 'linkedin'
  | 'phone'
  | 'meeting'
  | 'sales_page'
  | 'briefing'
  | 'video'
  | 'gift'
  | 'event'
  | 'content';

export type AEStep = {
  order: number;
  label: string;
  description: string;
  channel?: ActivityChannel;
};

export type ActivityCategory =
  | 'product'
  | 'event'
  | 'content_asset'
  | 'gift_touch'
  | 'customer_program'
  | 'deal_play';

export type ActivityDefinition = {
  id: string;
  name: string;
  category: ActivityCategory;
  description: string;
  aeSteps: AEStep[];
  targetSegment: string;
  engagementTargets: string;
  expectedOutcome: string;
  timing: string;
};

// ---------------------------------------------------------------------------
// Catalog
// ---------------------------------------------------------------------------

export const ACTIVITIES: ActivityDefinition[] = [
  // ── Product-related ─────────────────────────────────────────────────────
  {
    id: 'new_product_release',
    name: 'New Product Release',
    category: 'product',
    description: 'Major new product or platform launch.',
    aeSteps: [
      { order: 1, label: 'Build target list', description: 'Create target account list by product fit', channel: 'content' },
      { order: 2, label: 'Send product brief', description: 'Personalized email with product brief', channel: 'email' },
      { order: 3, label: 'Offer briefing or demo', description: 'Offer executive briefing or demo', channel: 'meeting' },
      { order: 4, label: 'Host launch webinar', description: 'Host launch webinar with Q&A', channel: 'event' },
      { order: 5, label: 'Follow up with ROI', description: 'Follow up with ROI calculator', channel: 'email' },
    ],
    targetSegment: 'Existing customers (cross-sell), strategic prospects with matching use case, accounts using competitor product',
    engagementTargets: 'C-Suite (CEO, CTO, CRO), department heads who own budget, current product champions, technical evaluators',
    expectedOutcome: '15-20% of engaged accounts book demo, 5-10% conversion to opportunity, upsell existing customers',
    timing: 'Launch week + 4 week follow-up campaign',
  },
  {
    id: 'new_feature_release',
    name: 'New Feature Release',
    category: 'product',
    description: 'Significant feature enhancement to existing product.',
    aeSteps: [
      { order: 1, label: 'Segment by relevance', description: 'Segment current customers by feature relevance', channel: 'content' },
      { order: 2, label: 'Send personalized message', description: "Send personalized 'built for you' message", channel: 'email' },
      { order: 3, label: 'Offer early access', description: 'Offer early access or beta participation', channel: 'email' },
      { order: 4, label: 'Create use cases', description: 'Create feature-specific use cases', channel: 'sales_page' },
      { order: 5, label: 'Schedule update calls', description: 'Schedule product update calls', channel: 'meeting' },
    ],
    targetSegment: 'Existing customers who requested feature, customers using workaround solutions, churned customers (win-back), prospects who said no due to missing feature',
    engagementTargets: 'Product users (day-to-day), department heads overseeing function, technical champions, previous detractors',
    expectedOutcome: '30-40% feature adoption by customers, win-back 10-15% of churned accounts, convert 5-8% of previous no prospects',
    timing: 'Launch day + 2 week adoption campaign',
  },
  {
    id: 'beta_program',
    name: 'Beta Program Invitation',
    category: 'product',
    description: 'Early access to upcoming features/products.',
    aeSteps: [
      { order: 1, label: 'Identify power users', description: 'Identify power users and champions', channel: 'content' },
      { order: 2, label: 'Send exclusive invite', description: 'Personalized invitation emphasizing exclusivity', channel: 'email' },
      { order: 3, label: 'Create feedback loop', description: 'Create beta feedback loop', channel: 'meeting' },
      { order: 4, label: 'Offer roadmap influence', description: 'Offer influence on roadmap', channel: 'meeting' },
      { order: 5, label: 'Leverage for case study', description: 'Leverage for case study/testimonial', channel: 'content' },
    ],
    targetSegment: 'Top 10-20% most engaged customers, strategic accounts, accounts with specific pain point beta solves, potential case study candidates',
    engagementTargets: 'Product power users, technical champions, innovation-focused executives, product managers at customer',
    expectedOutcome: 'Deepen relationship with strategic accounts, generate product feedback, create early advocates, 50%+ convert to case study',
    timing: '6-8 weeks before general release',
  },
  {
    id: 'product_roadmap_session',
    name: 'Product Roadmap Session',
    category: 'product',
    description: 'Exclusive preview of 6-12 month product plans.',
    aeSteps: [
      { order: 1, label: 'Invite top tier accounts', description: 'Invite top tier accounts only (top 20% by ARR)', channel: 'email' },
      { order: 2, label: 'Host session', description: 'Host intimate virtual or in-person session', channel: 'event' },
      { order: 3, label: 'Collect feedback', description: 'Collect feedback on priorities', channel: 'meeting' },
      { order: 4, label: 'Identify expansion', description: 'Identify expansion opportunities', channel: 'content' },
      { order: 5, label: 'Follow up with alignment', description: 'Follow up with custom roadmap alignment', channel: 'email' },
    ],
    targetSegment: 'Enterprise customers (high ARR), strategic accounts in expansion discussions, accounts at risk of churn, accounts evaluating competitors',
    engagementTargets: 'C-Suite (CTO, CRO, CEO), VP-level product stakeholders, champions who influence buying, technical decision makers',
    expectedOutcome: 'Increase retention of at-risk accounts, identify upsell opportunities, generate expansion pipeline, executive relationship building',
    timing: 'Quarterly (Q1, Q2, Q3, Q4)',
  },
  {
    id: 'integration_partnership',
    name: 'Integration Partnership Announcement',
    category: 'product',
    description: 'New integration with complementary platform.',
    aeSteps: [
      { order: 1, label: 'Identify dual users', description: 'Identify accounts using both platforms', channel: 'content' },
      { order: 2, label: 'Create joint use cases', description: 'Create joint use case documentation', channel: 'sales_page' },
      { order: 3, label: 'Co-host webinar', description: 'Co-host webinar with partner', channel: 'event' },
      { order: 4, label: 'Offer setup help', description: 'Offer integration setup assistance', channel: 'meeting' },
      { order: 5, label: 'Build combined ROI', description: 'Build combined ROI story', channel: 'content' },
    ],
    targetSegment: 'Customers using integration partner, prospects using integration partner, accounts who asked for integration, partner customer base (co-selling)',
    engagementTargets: 'Integration owners/admins, department heads using both tools, technical/IT stakeholders, executive sponsors of both platforms',
    expectedOutcome: '20-30% of dual users adopt integration, partner co-selling generates 10-15% net new pipeline, differentiation in competitive deals',
    timing: 'Partnership announcement + 6 week campaign',
  },
  {
    id: 'certification_compliance',
    name: 'Certification/Compliance Achievement',
    category: 'product',
    description: 'SOC2, ISO, GDPR, HIPAA, FedRAMP certification earned.',
    aeSteps: [
      { order: 1, label: 'Segment by compliance', description: 'Segment accounts by compliance requirement', channel: 'content' },
      { order: 2, label: 'Announce achievement', description: 'Announce achievement with proof points', channel: 'email' },
      { order: 3, label: 'Offer compliance docs', description: 'Offer compliance documentation package', channel: 'content' },
      { order: 4, label: 'Target blocked deals', description: 'Target previously blocked enterprise deals', channel: 'email' },
      { order: 5, label: 'Position for verticals', description: 'Position for regulated industries', channel: 'sales_page' },
    ],
    targetSegment: 'Enterprise prospects blocked by compliance, regulated industry accounts (healthcare, finance, govt), accounts in compliance audit mode, security-conscious buyers',
    engagementTargets: 'CISOs and security teams, compliance officers, legal/risk management, procurement (vendor management), IT leadership',
    expectedOutcome: 'Unblock 30-40% of stalled enterprise deals, enter new regulated verticals, reduce security objections by 50%',
    timing: 'Immediately upon certification + ongoing',
  },
  {
    id: 'price_packaging_change',
    name: 'Price/Packaging Change',
    category: 'product',
    description: 'New pricing tiers, packaging options, or special promotion.',
    aeSteps: [
      { order: 1, label: 'Grandfather customers', description: 'Grandfather existing customers proactively', channel: 'email' },
      { order: 2, label: 'Announce new options', description: 'Announce new options with upgrade paths', channel: 'email' },
      { order: 3, label: 'Create promotions', description: 'Create limited-time promotions', channel: 'sales_page' },
      { order: 4, label: 'Offer consultations', description: 'Offer pricing consultations', channel: 'meeting' },
      { order: 5, label: 'Position value', description: 'Position value over price', channel: 'content' },
    ],
    targetSegment: 'Existing customers (explain changes), price-sensitive prospects who said no, accounts stuck in procurement, smaller accounts ready to expand',
    engagementTargets: 'Economic buyers (CFO, VP Finance), department budget owners, procurement teams, current champions (arm them with new ROI)',
    expectedOutcome: 'Accelerate 15-20% of stalled deals, convert price objections to closes, upsell customers to higher tiers',
    timing: 'Announcement + 30-60 day promotion window',
  },

  // ── Events ──────────────────────────────────────────────────────────────
  {
    id: 'executive_dinner_intimate',
    name: 'Executive Dinner (Intimate)',
    category: 'event',
    description: 'Private dinner with 8-12 C-suite, curated guest list, strategic discussion.',
    aeSteps: [
      { order: 1, label: 'Identify strategic accounts', description: 'Identify 8-12 strategic accounts (mix of customers/prospects)', channel: 'content' },
      { order: 2, label: 'Send executive invite', description: 'Personalized invitation from your CEO/exec', channel: 'email' },
      { order: 3, label: 'Plan discussion topic', description: 'Plan discussion topic (not sales pitch)', channel: 'content' },
      { order: 4, label: 'Create seat mapping', description: 'Seat mapping for strategic conversations', channel: 'content' },
      { order: 5, label: 'Follow up within 48h', description: 'Follow-up within 48 hours with next steps', channel: 'email' },
    ],
    targetSegment: 'Top 5% of accounts by strategic value, mix: 60% customers (expand) / 40% tier-1 prospects, accounts in active deal cycles ($500K+)',
    engagementTargets: 'CEO, President, Founder, CRO, CTO, CFO (buyer personas), board members or advisors — ONE exec per company (exclusivity)',
    expectedOutcome: '60-70% advance to next stage, $2-5M pipeline per dinner, 3.4x higher pipeline/attendee vs large events',
    timing: 'Quarterly in major markets; 4-6 weeks notice',
  },
  {
    id: 'executive_dinner_larger',
    name: 'Executive Dinner (Larger)',
    category: 'event',
    description: 'Larger executive gathering with 15-20 attendees, panel discussion or fireside chat.',
    aeSteps: [
      { order: 1, label: 'Target accounts', description: 'Target 15-20 accounts (broader mix)', channel: 'content' },
      { order: 2, label: 'Include speakers', description: 'Include customer speakers/panelists', channel: 'meeting' },
      { order: 3, label: 'Structure content', description: 'Structure with formal content (45 min) + networking', channel: 'event' },
      { order: 4, label: 'Assign AEs', description: 'Assign AEs to specific attendees', channel: 'content' },
      { order: 5, label: 'Capture questions', description: 'Capture attendee questions for follow-up', channel: 'email' },
    ],
    targetSegment: 'Top 20% strategic accounts, mix: 50% customers / 50% prospects, accounts with $250K+ potential, regional clustering',
    engagementTargets: 'C-Suite and VP-level, buyer committee members, multiple contacts per account OK, customer advocates (speakers)',
    expectedOutcome: '40-50% progress deals forward, $1-3M pipeline per event, multi-threading into accounts',
    timing: 'Quarterly; 6 weeks notice; major cities',
  },
  {
    id: 'conference_booth',
    name: 'Conference Booth/Sponsorship',
    category: 'event',
    description: 'Industry conference presence with booth, speaking, or sponsorship.',
    aeSteps: [
      { order: 1, label: 'Pre-conference outreach', description: 'Pre-conference outreach (60 days before)', channel: 'email' },
      { order: 2, label: 'Book meetings', description: 'Book meetings in advance (target 20-30)', channel: 'meeting' },
      { order: 3, label: 'VIP hospitality', description: 'VIP lounge or hospitality suite for top accounts', channel: 'event' },
      { order: 4, label: 'Customer speaking', description: 'Speaking session with customer', channel: 'event' },
      { order: 5, label: 'Post-event follow-up', description: 'Post-event follow-up campaign (7 days)', channel: 'email' },
    ],
    targetSegment: 'Accounts attending conference, industry-specific targets, competitive accounts (displacement), expansion targets in existing customers',
    engagementTargets: 'Department heads attending, C-Suite if speaking, entire buying committees, champions to bring colleagues, competitive users',
    expectedOutcome: '40-50 qualified meetings, $3-5M pipeline from event, 20-30% of meetings become opportunity',
    timing: '60 days pre-event outreach through 7 days post',
  },
  {
    id: 'private_conference_suite',
    name: 'Private Conference Suite',
    category: 'event',
    description: 'Exclusive hospitality suite at major conference for invite-only meetings.',
    aeSteps: [
      { order: 1, label: 'Pre-book accounts', description: 'Pre-book 15-20 strategic accounts for time slots', channel: 'meeting' },
      { order: 2, label: 'Create VIP experience', description: 'Create invite-only experience (food, drinks, networking)', channel: 'event' },
      { order: 3, label: 'Schedule meetings', description: '1-on-1 or small group meetings', channel: 'meeting' },
      { order: 4, label: 'Bring executives', description: 'Bring executive team for face time', channel: 'meeting' },
      { order: 5, label: 'Capture next steps', description: 'Capture next steps in CRM immediately', channel: 'content' },
    ],
    targetSegment: 'Top tier accounts attending conference, active deal opportunities ($500K+), C-Suite prospects, key customer champions + their bosses',
    engagementTargets: 'C-Suite (exclusive access), VP-level buying committee, economic buyers, 2-3 people per account max',
    expectedOutcome: '70-80% of attendees advance deal stage, $5-10M pipeline from suite, high-quality face time',
    timing: 'Conference dates; book 6-8 weeks ahead',
  },
  {
    id: 'industry_roundtable',
    name: 'Industry Roundtable',
    category: 'event',
    description: 'Peer-to-peer discussion on industry challenges (10-15 attendees, similar roles).',
    aeSteps: [
      { order: 1, label: 'Curate attendee list', description: 'Curate attendee list by role (all VPs Sales, all CISOs, etc.)', channel: 'content' },
      { order: 2, label: 'Invite non-competing', description: 'Invite from non-competing companies', channel: 'email' },
      { order: 3, label: 'Facilitate discussion', description: 'Facilitate discussion (not sales pitch)', channel: 'event' },
      { order: 4, label: 'Capture insights', description: 'Capture challenges and insights', channel: 'content' },
      { order: 5, label: 'Share summary', description: 'Share summary report to attendees + follow-up', channel: 'email' },
    ],
    targetSegment: 'Accounts with same persona/role, non-competing companies, mix of customers (60%) and prospects (40%), target specific department/function',
    engagementTargets: 'Same role across companies (all CROs, all CTOs, all CMOs), VP-level for peer credibility',
    expectedOutcome: '50-60% of prospects become opportunity, thought leadership positioning, peer validation',
    timing: 'Quarterly; virtual or in-person; 4 weeks notice',
  },
  {
    id: 'webinar_educational',
    name: 'Webinar (Educational)',
    category: 'event',
    description: 'Educational content webinar on industry topic (100-500 attendees).',
    aeSteps: [
      { order: 1, label: 'Promote to targets', description: 'Promote to broad database + ABM targets', channel: 'email' },
      { order: 2, label: 'Partner with expert', description: 'Partner with industry expert/analyst', channel: 'meeting' },
      { order: 3, label: 'Include customer speaker', description: 'Include customer speaker for credibility', channel: 'event' },
      { order: 4, label: 'Live Q&A', description: 'Live Q&A to identify hot prospects', channel: 'event' },
      { order: 5, label: 'Segment follow-up', description: 'Segment follow-up by engagement level', channel: 'email' },
    ],
    targetSegment: 'Broad reach: all prospects + customers, early-stage prospects, accounts researching your category, customers (keep engaged, cross-sell)',
    engagementTargets: 'Directors and VPs, individual contributors (users), anyone researching the topic, multiple contacts per account welcome',
    expectedOutcome: '20-30% attendance rate, 5-10% of attendees become qualified opportunity, 100-200 new leads',
    timing: 'Monthly cadence; promote 2-3 weeks ahead',
  },
  {
    id: 'workshop_training',
    name: 'Workshop/Training Session',
    category: 'event',
    description: 'Hands-on workshop teaching specific skill or methodology (20-30 attendees).',
    aeSteps: [
      { order: 1, label: 'Target attendees', description: 'Target customers + high-intent prospects', channel: 'email' },
      { order: 2, label: 'Offer certification', description: 'Offer certification or credential', channel: 'content' },
      { order: 3, label: 'Run exercises', description: 'Hands-on exercises and breakouts', channel: 'event' },
      { order: 4, label: 'Bring experts', description: 'Bring product experts as instructors', channel: 'event' },
      { order: 5, label: 'Upsell features', description: 'Upsell advanced features during workshop', channel: 'meeting' },
    ],
    targetSegment: 'Current customers (adoption/expansion), late-stage prospects, accounts who need training/enablement, power users',
    engagementTargets: 'Product users (practitioners), team leads and managers, champions building business case, multiple users per account (5-10)',
    expectedOutcome: 'Increase product adoption by 40-50%, identify expansion opportunities, 30% of prospects convert post-workshop',
    timing: 'Quarterly; 3-4 weeks notice; virtual or in-person',
  },
  {
    id: 'executive_briefing_center',
    name: 'Executive Briefing Center Visit',
    category: 'event',
    description: 'On-site visit to company HQ for product demo and executive meeting.',
    aeSteps: [
      { order: 1, label: 'Invite strategic deals', description: 'Invite for strategic deals only ($1M+)', channel: 'email' },
      { order: 2, label: 'Coordinate visits', description: 'Coordinate with customer visits same day', channel: 'meeting' },
      { order: 3, label: 'Executive agenda', description: 'Executive agenda: vision, roadmap, partnership', channel: 'content' },
      { order: 4, label: 'Tailored demo', description: 'Product demo tailored to their use case', channel: 'meeting' },
      { order: 5, label: 'Tour and relationship', description: 'Tour facility, meet team, build relationship', channel: 'meeting' },
    ],
    targetSegment: 'Tier-1 strategic opportunities only, late-stage deals, customers considering expansion (7-figure), accounts requiring exec relationship',
    engagementTargets: 'C-Suite (CEO, CTO, CRO), buying committee (full team), technical decision makers, champion + their manager (3-5 people per account)',
    expectedOutcome: '80-90% close rate for visitors, accelerate deal velocity by 30-40%, build exec relationships',
    timing: 'For active deals; schedule 4-6 weeks ahead',
  },
  {
    id: 'user_conference',
    name: 'User Conference (Annual)',
    category: 'event',
    description: 'Annual customer conference with training, networking, product announcements (200+ attendees).',
    aeSteps: [
      { order: 1, label: 'Invite all customers', description: 'Invite all customers (prioritize top tier)', channel: 'email' },
      { order: 2, label: 'Free tickets for prospects', description: 'Offer free tickets to strategic prospects', channel: 'email' },
      { order: 3, label: 'Customer speakers', description: 'Customer speaking sessions', channel: 'event' },
      { order: 4, label: 'Roadmap reveals', description: 'Product roadmap reveals', channel: 'event' },
      { order: 5, label: 'Executive office hours', description: 'Executive office hours and expansion conversations', channel: 'meeting' },
    ],
    targetSegment: 'All customers (expansion targets), strategic prospects (top 50 accounts), power users, champions and executives',
    engagementTargets: 'Power users (training), department heads (strategy), executives (networking/roadmap), buying committee members, C-Suite (VIP)',
    expectedOutcome: '60-70% of customers attend, $10-20M expansion pipeline, 40-50% of prospects become opportunity',
    timing: 'Annual; 3-6 months planning; promote 8-12 weeks',
  },

  // ── Content & Assets ────────────────────────────────────────────────────
  {
    id: 'custom_research_report',
    name: 'Custom Research Report',
    category: 'content_asset',
    description: 'Original research, survey data, industry benchmarking report.',
    aeSteps: [
      { order: 1, label: 'Promote to targets', description: 'Promote report to target accounts', channel: 'email' },
      { order: 2, label: 'Offer benchmark', description: 'Offer personalized benchmark vs their data', channel: 'meeting' },
      { order: 3, label: 'Start conversation', description: 'Use as conversation starter (not sales pitch)', channel: 'phone' },
      { order: 4, label: 'Host findings webinar', description: 'Host webinar presenting findings', channel: 'event' },
      { order: 5, label: 'Account-specific insights', description: 'Follow up with account-specific insights', channel: 'email' },
    ],
    targetSegment: 'Accounts in target industries, C-Suite and VP-level, early-stage prospects, competitive accounts',
    engagementTargets: 'C-Suite (strategic insights), VPs and Directors (benchmarking), strategy/analytics teams, anyone researching industry trends',
    expectedOutcome: '25-35% download to meeting conversion, thought leadership positioning, sales conversation starters',
    timing: 'Annual or bi-annual; promote 4-6 weeks',
  },
  {
    id: 'roi_business_case',
    name: 'ROI/Business Case Tool',
    category: 'content_asset',
    description: 'Calculator or assessment tool showing value of your solution.',
    aeSteps: [
      { order: 1, label: 'Offer assessment', description: 'Offer personalized ROI assessment', channel: 'email' },
      { order: 2, label: 'Walk through calculator', description: 'Schedule call to walk through calculator', channel: 'meeting' },
      { order: 3, label: 'Deliver custom report', description: 'Deliver custom report with their numbers', channel: 'email' },
      { order: 4, label: 'Use in proposal', description: 'Use output in business case/proposal', channel: 'content' },
      { order: 5, label: 'Arm champion', description: 'Arm champion with exec-ready business case', channel: 'briefing' },
    ],
    targetSegment: 'Mid-to-late stage opportunities, accounts requiring CFO/finance approval, customers (expansion business case), champions building internal case',
    engagementTargets: 'Economic buyers (CFO, Finance), champions needing exec approval, procurement teams, department budget owners, C-Suite (final approvers)',
    expectedOutcome: '60-70% of users advance to next stage, reduce sales cycle by 20-30%, increase deal size',
    timing: 'For active opportunities; ongoing tool',
  },
  {
    id: 'customer_case_study',
    name: 'Customer Case Study',
    category: 'content_asset',
    description: 'Detailed success story with metrics and quotes from customer.',
    aeSteps: [
      { order: 1, label: 'Segment by industry', description: 'Segment case studies by industry/use case', channel: 'content' },
      { order: 2, label: 'Share with similar', description: 'Share with similar accounts (vertical/size)', channel: 'email' },
      { order: 3, label: 'Offer reference call', description: 'Offer customer reference call', channel: 'meeting' },
      { order: 4, label: 'Include in proposals', description: 'Include in proposals and follow-ups', channel: 'content' },
      { order: 5, label: 'Use in displacements', description: 'Use in competitive displacements', channel: 'sales_page' },
    ],
    targetSegment: 'Prospects in same industry, similar company size/stage, accounts with same use case, late-stage deals needing proof',
    engagementTargets: 'Buying committee members, skeptics/detractors in deal, C-Suite (exec-to-exec validation), technical teams (feasibility proof)',
    expectedOutcome: '50-60% request customer reference, increase close rate by 20-30%, reduce objections',
    timing: 'Release quarterly; use throughout sales cycle',
  },
  {
    id: 'analyst_report',
    name: 'Analyst Report/Validation',
    category: 'content_asset',
    description: 'Gartner, Forrester, or industry analyst coverage highlighting your solution.',
    aeSteps: [
      { order: 1, label: 'Share with enterprise', description: 'Share with enterprise accounts (analyst-driven)', channel: 'email' },
      { order: 2, label: 'Reference in pitches', description: 'Reference in proposals and pitches', channel: 'content' },
      { order: 3, label: 'Offer analyst briefing', description: 'Offer analyst briefing for strategic accounts', channel: 'meeting' },
      { order: 4, label: 'Overcome objections', description: 'Use to overcome competitive objections', channel: 'briefing' },
      { order: 5, label: 'Position as leader', description: 'Position as market leader/visionary', channel: 'sales_page' },
    ],
    targetSegment: 'Enterprise accounts (analyst-influenced), accounts using competitors in analyst report, procurement teams, strategic deals requiring validation',
    engagementTargets: 'C-Suite (strategic validation), IT/Technical buyers (analyst credibility), procurement/vendor management, enterprise architecture teams',
    expectedOutcome: 'Increase enterprise win rate by 30-40%, shorter vendor selection process, pricing power',
    timing: 'Ongoing; refresh when reports update',
  },
  {
    id: 'interactive_demo',
    name: 'Interactive Product Demo',
    category: 'content_asset',
    description: 'Self-service interactive demo or sandbox environment.',
    aeSteps: [
      { order: 1, label: 'Share in sequences', description: 'Share demo link in outreach sequences', channel: 'email' },
      { order: 2, label: 'Track engagement', description: 'Track engagement and usage patterns', channel: 'content' },
      { order: 3, label: 'Follow up on usage', description: 'Follow up based on features explored', channel: 'email' },
      { order: 4, label: 'Offer live walkthrough', description: 'Offer live walkthrough of specific features', channel: 'meeting' },
      { order: 5, label: 'Use as qualification', description: 'Use as qualification tool (time spent = intent)', channel: 'content' },
    ],
    targetSegment: 'Early-stage prospects, technical evaluators, accounts in multiple touches (nurture), inbound leads',
    engagementTargets: 'Technical users, product managers, individual contributors, champions building familiarity',
    expectedOutcome: '30-40% of engaged users become meeting, qualification tool (intent signal), reduce demo no-shows',
    timing: 'Ongoing; evergreen tool; track engagement',
  },
  {
    id: 'executive_video_message',
    name: 'Executive Video Message',
    category: 'content_asset',
    description: 'Personalized video from your executive to theirs addressing specific topic.',
    aeSteps: [
      { order: 1, label: 'Record custom video', description: 'Record custom video for strategic accounts', channel: 'video' },
      { order: 2, label: 'Reference challenge', description: 'Reference specific challenge or opportunity', channel: 'video' },
      { order: 3, label: 'Offer exec conversation', description: 'Offer exec-to-exec conversation', channel: 'meeting' },
      { order: 4, label: 'Use for breakthroughs', description: 'Use for breakthrough moments in stalled deals', channel: 'email' },
      { order: 5, label: 'Send via landing page', description: 'Send via personalized landing page', channel: 'sales_page' },
    ],
    targetSegment: 'Tier-1 strategic accounts (top 50), stalled deals needing executive intervention, key customer relationships, accounts ghosting/unresponsive',
    engagementTargets: 'CEO, President, Founder (peer-to-peer), C-Suite (CRO, CFO, CTO), only exec-level targets',
    expectedOutcome: '40-50% response rate, re-engage stalled deals, executive relationship building, differentiation',
    timing: 'For strategic accounts; ad-hoc; 2-3 min videos',
  },
  {
    id: 'competitive_battlecard',
    name: 'Competitive Battlecard/Comparison',
    category: 'content_asset',
    description: 'Detailed comparison showing your advantages vs competitors.',
    aeSteps: [
      { order: 1, label: 'Share in deal', description: 'Share when competitor is in the deal', channel: 'email' },
      { order: 2, label: 'Highlight differentiation', description: 'Highlight differentiation and TCO analysis', channel: 'briefing' },
      { order: 3, label: 'Offer trial/POC', description: 'Offer trial/POC to prove superiority', channel: 'meeting' },
      { order: 4, label: 'Arm champion', description: 'Arm champion with competitive talking points', channel: 'briefing' },
      { order: 5, label: 'Position on value', description: 'Position on value, not just features', channel: 'sales_page' },
    ],
    targetSegment: 'Accounts actively evaluating competitors, competitive displacement targets, accounts using competitor (expansion blocked), bake-off situations',
    engagementTargets: 'Technical evaluators, economic buyers (TCO/ROI), champions (arm with differentiation), buying committee (vendor selection)',
    expectedOutcome: 'Win 50-60% of competitive deals, increase deal size, reduce discounting pressure',
    timing: 'For competitive deals; keep updated quarterly',
  },
  {
    id: 'personalized_video_demo',
    name: 'Personalized Video Demo',
    category: 'content_asset',
    description: "Custom recorded demo addressing prospect's specific use case and pain points.",
    aeSteps: [
      { order: 1, label: 'Record personalized demo', description: 'Record 5-10 min demo using their name/company', channel: 'video' },
      { order: 2, label: 'Show their problem', description: 'Show exactly how you solve their stated problem', channel: 'video' },
      { order: 3, label: 'Include their data', description: 'Include their data/scenarios where possible', channel: 'video' },
      { order: 4, label: 'Send via platform', description: 'Send via video platform (track viewing)', channel: 'email' },
      { order: 5, label: 'Follow up if viewed', description: 'Follow up within 24 hours of viewing', channel: 'email' },
    ],
    targetSegment: 'Mid-stage prospects post-discovery, accounts with specific/unique use case, multiple stakeholders needing alignment, accounts who cannot attend live demo',
    engagementTargets: 'Buying committee members (async viewing), stakeholders who missed live demo, technical evaluators, champions to share internally',
    expectedOutcome: '60-70% view rate, multi-threading (shareable), 40% of viewers advance to next stage',
    timing: 'After discovery call; 48 hour turnaround',
  },

  // ── Gifts & Touches ─────────────────────────────────────────────────────
  {
    id: 'high_value_gift',
    name: 'High-Value Executive Gift',
    category: 'gift_touch',
    description: 'Premium gift ($200-500) for top-tier accounts.',
    aeSteps: [
      { order: 1, label: 'Research interests', description: 'Research personal interests (LinkedIn, social)', channel: 'content' },
      { order: 2, label: 'Personalized note', description: 'Personalized note from your executive', channel: 'gift' },
      { order: 3, label: 'Send gift', description: 'Send to home or office (permission-based)', channel: 'gift' },
      { order: 4, label: 'No immediate ask', description: 'No immediate ask (relationship building)', channel: 'content' },
      { order: 5, label: 'Follow up later', description: 'Follow up 1-2 weeks later with meeting request', channel: 'email' },
    ],
    targetSegment: 'Top 20 strategic accounts, active deals over $500K, key customer executives (retention/expansion), hard-to-reach prospects',
    engagementTargets: 'C-Suite only (CEO, CRO, CFO, CTO), ultimate decision makers, executive champions at customers, one per account',
    expectedOutcome: '50-60% response rate, relationship building, breakthrough with hard-to-reach execs',
    timing: 'Strategic timing: deal milestones, holidays, birthdays',
  },
  {
    id: 'lower_value_gift',
    name: 'Thoughtful Lower-Value Gift',
    category: 'gift_touch',
    description: 'Personalized gift under $100 (books, snacks, company swag, local gifts).',
    aeSteps: [
      { order: 1, label: 'Tie to conversation', description: 'Tie to specific conversation or interest', channel: 'content' },
      { order: 2, label: 'Personalized note', description: 'Personalized note referencing discussion', channel: 'gift' },
      { order: 3, label: 'Send to multiple', description: 'Send to multiple contacts at account', channel: 'gift' },
      { order: 4, label: 'Use as touchpoint', description: 'Use as touchpoint in nurture sequence', channel: 'email' },
      { order: 5, label: 'Follow up', description: 'Follow up with relevant content or meeting ask', channel: 'email' },
    ],
    targetSegment: 'Mid-stage opportunities, champions and influencers, accounts in nurture, post-demo follow-up',
    engagementTargets: 'Buying committee members, champions and influencers, department heads, technical evaluators, multiple contacts per account OK',
    expectedOutcome: '30-40% response rate, stay top-of-mind during eval, build rapport with champions',
    timing: 'Throughout sales cycle; after key milestones',
  },
  {
    id: 'charitable_donation',
    name: 'Charitable Donation in Their Name',
    category: 'gift_touch',
    description: "Donate to charity they care about in their/company's name.",
    aeSteps: [
      { order: 1, label: 'Research initiatives', description: "Research company's charitable initiatives", channel: 'content' },
      { order: 2, label: 'Make donation', description: 'Make donation and send certificate/acknowledgment', channel: 'gift' },
      { order: 3, label: 'Values-based note', description: 'Personalized note about shared values', channel: 'email' },
      { order: 4, label: 'No sales ask', description: 'No immediate sales ask (goodwill)', channel: 'content' },
      { order: 5, label: 'Follow up 2 weeks', description: 'Follow up 2 weeks later', channel: 'email' },
    ],
    targetSegment: 'Accounts with strong CSR/social mission, executives with public charitable affiliations, post-deal thank you, non-profit organizations',
    engagementTargets: 'C-Suite (values-based connection), sustainability/CSR officers, founder/CEO, executive sponsors at customers',
    expectedOutcome: 'Values-based relationship building, differentiation (not transactional), 40-50% respond positively',
    timing: 'Strategic: end-of-year, after deal close, awareness months',
  },
  {
    id: 'personalized_research',
    name: 'Personalized Research/Insight',
    category: 'gift_touch',
    description: 'Custom analysis, competitive intel, or market research specific to their company.',
    aeSteps: [
      { order: 1, label: 'Research company', description: "Research their company's challenges/market", channel: 'content' },
      { order: 2, label: 'Create insight doc', description: 'Create custom insight document or analysis', channel: 'content' },
      { order: 3, label: 'Pure value delivery', description: "No product pitch — pure value, position as 'thought this would help'", channel: 'email' },
      { order: 4, label: 'Offer deeper dive', description: 'Follow up offering deeper dive conversation', channel: 'meeting' },
    ],
    targetSegment: 'Strategic accounts, stalled deals (re-engage with value), hard-to-reach prospects, accounts in research/planning phase',
    engagementTargets: 'C-Suite (strategic insights), strategy/analytics teams, department heads, champions needing ammunition',
    expectedOutcome: '50-60% response rate, thought leadership positioning, build trust through value',
    timing: 'After research; ad-hoc; for breakthrough moments',
  },
  {
    id: 'event_tickets',
    name: 'Tickets to Event/Experience',
    category: 'gift_touch',
    description: 'Sports, concert, theater, or experience tickets for prospects/customers.',
    aeSteps: [
      { order: 1, label: 'Research interests', description: 'Identify personal interests (social media research)', channel: 'content' },
      { order: 2, label: 'Offer tickets', description: 'Offer 2-4 tickets (bring family/colleagues)', channel: 'email' },
      { order: 3, label: 'Attend together', description: 'Optional: attend together (relationship building)', channel: 'meeting' },
      { order: 4, label: 'No sales talk', description: 'No sales talk during event (pure networking)', channel: 'meeting' },
      { order: 5, label: 'Follow up after', description: 'Follow up after event with meeting request', channel: 'email' },
    ],
    targetSegment: 'Top 50 strategic accounts, active deals over $250K, key customer executives, hard-to-reach decision makers',
    engagementTargets: 'C-Suite and VP-level, economic buyers, executive champions, offer 2-4 tickets (bring guest)',
    expectedOutcome: 'Relationship deepening, face time in relaxed setting, 60-70% leads to business conversation',
    timing: 'Based on local events; plan 4-6 weeks ahead',
  },
  {
    id: 'lunch_learn',
    name: 'Lunch & Learn Sponsorship',
    category: 'gift_touch',
    description: 'Sponsor lunch/coffee for their team with educational session.',
    aeSteps: [
      { order: 1, label: 'Offer lunch for team', description: 'Offer to bring lunch for their team (15-30 people)', channel: 'email' },
      { order: 2, label: 'Educational workshop', description: 'Educational workshop or training (not sales pitch)', channel: 'event' },
      { order: 3, label: 'Bring expert speaker', description: 'Bring your product expert or customer speaker', channel: 'event' },
      { order: 4, label: 'Hands-on learning', description: 'Hands-on learning or Q&A', channel: 'meeting' },
      { order: 5, label: 'Multi-thread', description: 'Multi-thread into multiple users at account', channel: 'linkedin' },
    ],
    targetSegment: 'Mid-to-late stage opportunities, customers (expand into new department), accounts with multiple users, team-based buying',
    engagementTargets: 'Entire team/department (15-30 people), mix of users, managers, and leaders, champions bring colleagues',
    expectedOutcome: 'Multi-threading (meet 10-20 contacts), build consensus across team, 50-60% advance opportunity',
    timing: 'For active deals; coordinate 2-3 weeks ahead',
  },
  {
    id: 'ae_video_message',
    name: 'Personalized Video Message (AE)',
    category: 'gift_touch',
    description: 'Short personalized video from AE to prospect addressing specific point.',
    aeSteps: [
      { order: 1, label: 'Record short video', description: 'Record 1-2 min video using their name', channel: 'video' },
      { order: 2, label: 'Reference pain point', description: 'Reference specific conversation or pain point', channel: 'video' },
      { order: 3, label: 'Send and track', description: 'Share via Vidyard, Loom, etc. (track viewing)', channel: 'email' },
      { order: 4, label: 'Human touch', description: 'Human touch in email sequence', channel: 'email' },
      { order: 5, label: 'Follow up if viewed', description: 'Follow up within 24 hours if viewed', channel: 'email' },
    ],
    targetSegment: 'All prospects (scalable personalization), early-stage outreach, follow-up after meetings, unresponsive prospects',
    engagementTargets: 'All buyer personas, champions and influencers, anyone in sales process, scalable to high volume',
    expectedOutcome: '2-3x higher response vs text email, humanize outreach, 30-40% view rate',
    timing: 'Throughout sales cycle; 5-10 min to create',
  },
  {
    id: 'swag_merchandise',
    name: 'Swag/Company Merchandise',
    category: 'gift_touch',
    description: 'Branded swag (apparel, tech accessories, drinkware) sent to prospects/customers.',
    aeSteps: [
      { order: 1, label: 'Send at milestones', description: 'Send after key milestones (demo, proposal, close)', channel: 'gift' },
      { order: 2, label: 'Include note', description: 'Include personalized note', channel: 'gift' },
      { order: 3, label: 'Conference promos', description: "Use for conference promotions ('stop by booth')", channel: 'email' },
      { order: 4, label: 'Champion appreciation', description: 'Send to champions (make them feel valued)', channel: 'gift' },
      { order: 5, label: 'Customer touchpoint', description: 'Customer appreciation touchpoint', channel: 'gift' },
    ],
    targetSegment: 'All stages (scalable and low-cost), conference attendees, champions and advocates, customers',
    engagementTargets: 'All contacts (low cost = high volume), champions and heavy users, conference targets, new customer onboarding',
    expectedOutcome: 'Brand awareness and recall, customer appreciation, conference booth traffic increase',
    timing: 'Ongoing; after milestones; conference lead-up',
  },

  // ── Customer Programs ───────────────────────────────────────────────────
  {
    id: 'customer_reference_program',
    name: 'Customer Reference Program',
    category: 'customer_program',
    description: 'Formal program offering incentives for customers who provide references.',
    aeSteps: [
      { order: 1, label: 'Identify top customers', description: 'Identify top 20% most successful customers', channel: 'content' },
      { order: 2, label: 'Recruit with incentives', description: 'Recruit into program with incentives (credits, gifts, priority support)', channel: 'email' },
      { order: 3, label: 'Match references', description: 'Match references to similar prospects', channel: 'content' },
      { order: 4, label: 'Schedule calls', description: 'Schedule reference calls for key deals', channel: 'meeting' },
      { order: 5, label: 'Track and reward', description: 'Track and reward participation', channel: 'content' },
    ],
    targetSegment: 'Highly satisfied customers (NPS 9-10), customers with measurable results, executive champions, customers in target industries',
    engagementTargets: 'C-Suite (exec-to-exec references), department heads (peer validation), power users (product validation), champions',
    expectedOutcome: '70-80% of reference-backed deals close, 30% higher close rates, reduce sales cycle by 20-30%',
    timing: 'Recruit quarterly; use ongoing in sales cycle',
  },
  {
    id: 'case_study_creation',
    name: 'Customer Case Study Creation',
    category: 'customer_program',
    description: 'Co-create detailed success story with customer for marketing use.',
    aeSteps: [
      { order: 1, label: 'Identify candidates', description: 'Identify customers with strong results (3-5 per quarter)', channel: 'content' },
      { order: 2, label: 'Interview customer', description: 'Interview customer and capture metrics', channel: 'meeting' },
      { order: 3, label: 'Create assets', description: 'Create multi-format assets (written, video, one-pager)', channel: 'content' },
      { order: 4, label: 'Promote to similar', description: 'Promote to similar prospects', channel: 'email' },
      { order: 5, label: 'Reward customer', description: 'Reward customer (publicity, gift, relationship)', channel: 'gift' },
    ],
    targetSegment: 'Customers with 3-12 months of results, measurable outcomes, target industries or use cases, willing to go public',
    engagementTargets: 'Executive sponsors (quotes and approval), product users (hands-on details), department heads (business outcomes), champions',
    expectedOutcome: '15-20 quality case studies annually, increase win rate by 25-30%, shorten sales cycle',
    timing: '3-6 months post-implementation; quarterly cadence',
  },
  {
    id: 'customer_advisory_board',
    name: 'Customer Advisory Board',
    category: 'customer_program',
    description: 'Exclusive group of strategic customers who influence product roadmap.',
    aeSteps: [
      { order: 1, label: 'Invite top customers', description: 'Invite top 15-20 customers (by ARR + strategic fit)', channel: 'email' },
      { order: 2, label: 'Quarterly meetings', description: 'Quarterly meetings with product team', channel: 'meeting' },
      { order: 3, label: 'Influence roadmap', description: 'Influence roadmap and provide feedback', channel: 'meeting' },
      { order: 4, label: 'Executive networking', description: 'Executive networking and peer learning', channel: 'event' },
      { order: 5, label: 'VIP treatment', description: 'VIP treatment (retention + expansion)', channel: 'gift' },
    ],
    targetSegment: 'Top 10% of customers by ARR, strategic/lighthouse accounts, customers representing key segments, product-engaged and vocal customers',
    engagementTargets: 'C-Suite (CEO, CTO, CRO), VP-level product stakeholders, champions with influence, 1-2 people per customer company',
    expectedOutcome: '95%+ retention of CAB members, $5-10M expansion pipeline, product-market fit validation',
    timing: 'Quarterly meetings; recruit annually; 12-month term',
  },
  {
    id: 'customer_awards',
    name: 'Customer Awards Program',
    category: 'customer_program',
    description: 'Recognize top customers with awards (Innovation, Growth, Impact, etc.).',
    aeSteps: [
      { order: 1, label: 'Create categories', description: 'Create award categories tied to business outcomes', channel: 'content' },
      { order: 2, label: 'Select winners', description: 'Nominate and select winners (3-5 per category)', channel: 'content' },
      { order: 3, label: 'Announce publicly', description: 'Announce at user conference or publicly', channel: 'event' },
      { order: 4, label: 'Create case studies', description: 'Create case studies of winners', channel: 'content' },
      { order: 5, label: 'Use for advocacy', description: 'Use for advocacy and references', channel: 'email' },
    ],
    targetSegment: 'Top performing customers, customers achieving remarkable results, strategic accounts to honor (retention), customers in target expansion segments',
    engagementTargets: 'C-Suite (recognition at exec level), department heads (category winners), champions (personal recognition), power users (technical awards)',
    expectedOutcome: 'Customer retention (honored customers stay), advocacy (winners willing to reference), case study content creation',
    timing: 'Annual awards; announce at user conference',
  },
  {
    id: 'co_marketing',
    name: 'Co-Marketing Opportunity',
    category: 'customer_program',
    description: 'Joint marketing initiative with customer (webinar, content, event).',
    aeSteps: [
      { order: 1, label: 'Identify partners', description: 'Identify customers willing to co-present', channel: 'content' },
      { order: 2, label: 'Create joint content', description: 'Create joint content (webinar, blog, video)', channel: 'content' },
      { order: 3, label: 'Co-promote', description: 'Co-promote to both audiences', channel: 'email' },
      { order: 4, label: 'Customer exposure', description: 'Customer gets exposure + thought leadership', channel: 'event' },
      { order: 5, label: 'Credibility + reach', description: 'You get credibility + new prospect reach', channel: 'email' },
    ],
    targetSegment: 'Customers with strong results and story, marketing-savvy customers, customers in high-value target segments, strategic accounts for deeper relationship',
    engagementTargets: 'Customer marketing teams (co-promotion), customer executives (co-presenting), customer subject matter experts (content)',
    expectedOutcome: 'Reach customer audience (net new prospects), social proof, customer retention, 10-20 new opportunities per initiative',
    timing: '2-3 per quarter; plan 6-8 weeks ahead',
  },
  {
    id: 'executive_business_review',
    name: 'Executive Business Review (QBR)',
    category: 'customer_program',
    description: 'Quarterly strategic review with customer executive showing value delivered.',
    aeSteps: [
      { order: 1, label: 'Prepare custom report', description: 'Prepare custom report with metrics/outcomes', channel: 'content' },
      { order: 2, label: 'Schedule with sponsor', description: 'Schedule with executive sponsor + team', channel: 'meeting' },
      { order: 3, label: 'Review success', description: 'Review success, challenges, and roadmap', channel: 'meeting' },
      { order: 4, label: 'Identify expansion', description: 'Identify expansion opportunities', channel: 'content' },
      { order: 5, label: 'Align on goals', description: 'Align on mutual goals for next quarter', channel: 'meeting' },
    ],
    targetSegment: 'All enterprise customers (ACV $100K+), at-risk accounts, expansion targets, executive relationships to maintain',
    engagementTargets: 'Executive sponsor (C-Suite or VP), department heads using product, champions and power users, your account team (AE, CSM, exec)',
    expectedOutcome: '80%+ retention for accounts with regular QBRs, identify 30-40% expansion opportunities, proactive issue resolution',
    timing: 'Quarterly; schedule 4 weeks ahead; 60-90 min',
  },
  {
    id: 'customer_expansion_workshop',
    name: 'Customer Expansion Workshop',
    category: 'customer_program',
    description: 'Dedicated session to explore additional use cases and departments.',
    aeSteps: [
      { order: 1, label: 'Review current usage', description: 'Review current usage and adoption', channel: 'content' },
      { order: 2, label: 'Identify unused features', description: 'Identify unused features and capabilities', channel: 'meeting' },
      { order: 3, label: 'Map departments', description: 'Map other departments with similar needs', channel: 'content' },
      { order: 4, label: 'Create expansion case', description: 'Create expansion business case', channel: 'briefing' },
      { order: 5, label: 'Intro to new stakeholders', description: 'Introduce to new department stakeholders', channel: 'meeting' },
    ],
    targetSegment: 'Customers with strong adoption in one department, customers with expansion potential, customers post-renewal, strategic accounts (land and expand)',
    engagementTargets: 'Current department heads, champions (expand from), new department heads, cross-functional leaders, executive sponsor',
    expectedOutcome: '50-60% result in expansion opportunity, $50-200K average expansion ARR, multi-department adoption',
    timing: '6-12 months post-implementation; bi-annual',
  },
  {
    id: 'customer_testimonial_video',
    name: 'Customer Testimonial (Video)',
    category: 'customer_program',
    description: 'Produce professional video testimonial with customer.',
    aeSteps: [
      { order: 1, label: 'Identify willing customers', description: 'Identify willing customers with great stories', channel: 'content' },
      { order: 2, label: 'Coordinate production', description: 'Coordinate video production (hire crew or DIY)', channel: 'meeting' },
      { order: 3, label: 'Customer interview', description: 'Customer interview format (3-5 min)', channel: 'video' },
      { order: 4, label: 'Edit formats', description: 'Edit into multiple formats (short clips, full length)', channel: 'content' },
      { order: 5, label: 'Use across channels', description: 'Use across website, sales, and social', channel: 'sales_page' },
    ],
    targetSegment: 'Highly satisfied customers (NPS 9-10), customers with compelling visual story, articulate spokespeople, target industries',
    engagementTargets: 'Executive sponsors (C-Suite quotes), department heads, power users, champions (enthusiastic advocates)',
    expectedOutcome: '3-5 quality videos per year, website conversion increase (20-30%), sales enablement (send in sequences)',
    timing: '6-12 months post-implementation; plan 6-8 weeks',
  },
  {
    id: 'customer_social_advocacy',
    name: 'Customer Advocacy on Social',
    category: 'customer_program',
    description: 'Encourage/facilitate customers sharing success on LinkedIn, Twitter, etc.',
    aeSteps: [
      { order: 1, label: 'Provide draft posts', description: 'Provide draft social posts to customers', channel: 'content' },
      { order: 2, label: 'Tag customer', description: 'Tag customer in your posts about their success', channel: 'linkedin' },
      { order: 3, label: 'Engage with posts', description: "Engage with customer's organic posts", channel: 'linkedin' },
      { order: 4, label: 'Run spotlight series', description: "Run 'customer spotlight' series on social", channel: 'content' },
      { order: 5, label: 'Reward advocates', description: 'Reward most active advocates', channel: 'gift' },
    ],
    targetSegment: 'All satisfied customers, champions active on social media, customers with recent wins/results, customers seeking thought leadership',
    engagementTargets: 'Champions (personal brand building), marketing teams (co-promotion), executives (thought leadership), power users (community engagement)',
    expectedOutcome: 'Organic social proof, reach new audiences via customers, build customer community, identify and activate advocates',
    timing: 'Ongoing; provide monthly content suggestions',
  },

  // ── Deal Plays ──────────────────────────────────────────────────────────
  {
    id: 'free_trial',
    name: 'Free Trial / Freemium',
    category: 'deal_play',
    description: 'Self-service free trial (14-30 days) or freemium tier.',
    aeSteps: [
      { order: 1, label: 'Promote trial', description: 'Promote trial in outreach sequences', channel: 'email' },
      { order: 2, label: 'Track usage', description: 'Track trial usage and engagement', channel: 'content' },
      { order: 3, label: 'Sales touchpoints', description: 'Trigger sales touchpoints based on behavior', channel: 'email' },
      { order: 4, label: 'White-glove onboarding', description: 'Offer white-glove onboarding to high-value accounts', channel: 'meeting' },
      { order: 5, label: 'Convert to paid', description: 'Convert to paid with limited-time offer', channel: 'email' },
    ],
    targetSegment: 'SMB and mid-market (self-service), early-stage prospects, individual users (bottoms-up adoption), price-sensitive buyers',
    engagementTargets: 'Individual contributors (end users), team leads, small business owners, anyone wanting hands-on experience',
    expectedOutcome: '20-30% trial-to-paid conversion, product-qualified leads, reduce sales cycle for SMB, bottoms-up enterprise adoption',
    timing: 'Ongoing; evergreen; 14-30 day trial period',
  },
  {
    id: 'proof_of_concept',
    name: 'Proof of Concept (POC)',
    category: 'deal_play',
    description: 'Structured evaluation period (30-90 days) with defined success criteria.',
    aeSteps: [
      { order: 1, label: 'Define success criteria', description: 'Agree on success criteria upfront (mutual close plan)', channel: 'meeting' },
      { order: 2, label: 'Dedicated onboarding', description: 'Dedicated onboarding and support', channel: 'meeting' },
      { order: 3, label: 'Weekly check-ins', description: 'Weekly check-ins and progress tracking', channel: 'meeting' },
      { order: 4, label: 'Capture wins', description: 'Capture wins and business value', channel: 'content' },
      { order: 5, label: 'Convert to paid', description: 'Convert to paid with seamless transition', channel: 'meeting' },
    ],
    targetSegment: 'Enterprise deals ($250K+), complex technical evaluations, accounts requiring proof before commitment, risk-averse buyers',
    engagementTargets: 'Technical evaluators, department heads, executive sponsor, full buying committee (consensus)',
    expectedOutcome: '60-70% POC-to-close rate, de-risk large deals, demonstrate ROI with real data, build champions',
    timing: 'Late-stage deals; 30-90 days; mutual close plan',
  },
  {
    id: 'pilot_program',
    name: 'Pilot Program',
    category: 'deal_play',
    description: 'Limited deployment in one department/region before full rollout.',
    aeSteps: [
      { order: 1, label: 'Define pilot scope', description: 'Define pilot scope (one team, one use case)', channel: 'meeting' },
      { order: 2, label: 'Measure outcomes', description: 'Measure outcomes vs baseline', channel: 'content' },
      { order: 3, label: 'Create success story', description: 'Create success story from pilot', channel: 'content' },
      { order: 4, label: 'Expand to others', description: 'Expand to other departments/regions', channel: 'meeting' },
      { order: 5, label: 'Use results in case', description: 'Use pilot results in business case for expansion', channel: 'briefing' },
    ],
    targetSegment: 'Enterprise accounts (land and expand), accounts with multi-department potential, risk-averse organizations, customers considering expansion',
    engagementTargets: 'One department/team for pilot (10-50 users), department head (pilot sponsor), executive sponsor, champions in pilot department',
    expectedOutcome: '70-80% pilots expand to full rollout, internal proof point, reduce perceived risk, average 5-10x expansion',
    timing: 'Initial sale or expansion; 60-90 day pilot',
  },
  {
    id: 'competitive_displacement',
    name: 'Competitive Displacement Play',
    category: 'deal_play',
    description: 'Structured program to win accounts from specific competitor.',
    aeSteps: [
      { order: 1, label: 'Identify competitor accounts', description: 'Identify accounts using target competitor', channel: 'content' },
      { order: 2, label: 'Research weaknesses', description: 'Research competitor weaknesses and customer complaints', channel: 'content' },
      { order: 3, label: 'Build differentiation', description: 'Build competitive differentiation messaging', channel: 'sales_page' },
      { order: 4, label: 'Offer migration help', description: 'Offer migration assistance and incentives', channel: 'email' },
      { order: 5, label: 'Risk reversal', description: 'Risk-reversal guarantees (easy switch-back if not satisfied)', channel: 'meeting' },
    ],
    targetSegment: 'Accounts using specific competitor, accounts in competitor renewal window, accounts with public complaints, competitor unhappy customers',
    engagementTargets: 'Economic buyers (cost/value comparison), technical evaluators, end users (frustrated with competitor), champions (internal advocates for change)',
    expectedOutcome: '20-30% competitive win rate (targeted), premium pricing vs competitor, market share gains',
    timing: 'Target renewal windows; ongoing competitive intel',
  },
  {
    id: 'renewal_expansion',
    name: 'Renewal Expansion Play',
    category: 'deal_play',
    description: 'Strategic upsell during customer renewal period.',
    aeSteps: [
      { order: 1, label: 'Start early', description: 'Start renewal conversation 90-120 days early', channel: 'email' },
      { order: 2, label: 'Usage review', description: 'Conduct usage review and identify expansion opportunities', channel: 'meeting' },
      { order: 3, label: 'Build expansion case', description: 'Build expansion business case with ROI', channel: 'briefing' },
      { order: 4, label: 'Bundle renewal', description: 'Bundle renewal + expansion with discount', channel: 'meeting' },
      { order: 5, label: 'Multi-year deal', description: 'Multi-year deal for price lock', channel: 'meeting' },
    ],
    targetSegment: 'All customers approaching renewal (90 days out), customers with high engagement, customers with unused features, strategic accounts',
    engagementTargets: 'Executive sponsor (renewal approval), economic buyer, department heads (expansion sponsors), champions, CSM + AE partnership',
    expectedOutcome: '40-50% of renewals include expansion, average 20-30% ARR growth at renewal, multi-year lock-in',
    timing: 'Start 90-120 days before renewal; close 30 days before',
  },
  {
    id: 'executive_sponsorship',
    name: 'Executive Sponsorship Program',
    category: 'deal_play',
    description: 'Assign your exec as strategic advisor to customer exec (top accounts only).',
    aeSteps: [
      { order: 1, label: 'Match executives', description: 'Match your exec with customer exec (peer level)', channel: 'meeting' },
      { order: 2, label: 'Quarterly check-ins', description: 'Quarterly strategic check-ins (not tactical)', channel: 'meeting' },
      { order: 3, label: 'Advisory role', description: 'Advisory on industry trends and best practices', channel: 'meeting' },
      { order: 4, label: 'Network access', description: 'Access to network and resources', channel: 'meeting' },
      { order: 5, label: 'VIP treatment', description: 'VIP treatment and relationship building', channel: 'gift' },
    ],
    targetSegment: 'Top 10-20 accounts by ARR, accounts with potential for 3-5x growth, at-risk accounts needing executive attention, lighthouse accounts',
    engagementTargets: 'Customer C-Suite (CEO, CRO, CFO, CTO), your C-Suite (matched peer-to-peer), 1:1 executive relationship, quarterly touchpoints',
    expectedOutcome: '95%+ retention of sponsored accounts, 2-3x expansion vs non-sponsored, executive champions created',
    timing: 'Top tier accounts; ongoing relationship; quarterly meetings',
  },
  {
    id: 'champion_development',
    name: 'Champion Development Program',
    category: 'deal_play',
    description: 'Systematic approach to identifying and empowering internal champions.',
    aeSteps: [
      { order: 1, label: 'Identify champions', description: 'Identify potential champions (engaged users)', channel: 'content' },
      { order: 2, label: 'Provide enablement', description: 'Provide champion enablement (tools, content, swag)', channel: 'briefing' },
      { order: 3, label: 'Arm with business case', description: 'Arm with business case and ROI data', channel: 'content' },
      { order: 4, label: 'Connect champions', description: 'Connect champions across customer accounts (community)', channel: 'event' },
      { order: 5, label: 'Reward contributions', description: 'Reward and recognize champion contributions', channel: 'gift' },
    ],
    targetSegment: 'All accounts with engaged users, mid-to-late stage deals, customers (expansion advocates), accounts with political complexity',
    engagementTargets: 'Power users (day-to-day champions), mid-level managers, directors/VPs (executive champions), anyone who loves your product',
    expectedOutcome: '80%+ close rate with strong champion, faster sales cycles, multi-threading via champion introductions',
    timing: 'Throughout sales cycle; identify early; nurture ongoing',
  },
  {
    id: 'multi_year_deal',
    name: 'Multi-Year Deal Incentive',
    category: 'deal_play',
    description: 'Significant discount for 2-3 year commitment vs annual.',
    aeSteps: [
      { order: 1, label: 'Offer in proposals', description: 'Offer multi-year pricing in proposals', channel: 'content' },
      { order: 2, label: 'Emphasize predictability', description: 'Emphasize price lock and budget predictability', channel: 'meeting' },
      { order: 3, label: 'Reduce friction', description: 'Reduce annual renewal friction', channel: 'meeting' },
      { order: 4, label: 'Growth tiers', description: 'Include growth tiers for expansion', channel: 'content' },
      { order: 5, label: 'Financial incentive', description: 'Financial incentive for commitment', channel: 'email' },
    ],
    targetSegment: 'Accounts with strong product-market fit, customers at renewal, late-stage prospects, budget-conscious buyers',
    engagementTargets: 'CFO and Finance (budget planning), economic buyers, procurement, executive sponsor',
    expectedOutcome: '20-30% higher deal value, lock in revenue (reduce churn risk), faster close',
    timing: 'For closing deals and renewals; ongoing offer',
  },
  {
    id: 'bundle_package_deal',
    name: 'Bundle/Package Deal',
    category: 'deal_play',
    description: 'Combine multiple products or tiers at discounted package price.',
    aeSteps: [
      { order: 1, label: 'Identify cross-sell', description: 'Identify customers using only one product (cross-sell)', channel: 'content' },
      { order: 2, label: 'Create bundle offer', description: 'Create bundled offer (product A + B at discount)', channel: 'sales_page' },
      { order: 3, label: 'Position together', description: "Position as 'better together' value", channel: 'email' },
      { order: 4, label: 'Solve multiple pains', description: 'Solve multiple pain points in one deal', channel: 'meeting' },
      { order: 5, label: 'Upsell bundle', description: 'Upsell bundle vs single product', channel: 'meeting' },
    ],
    targetSegment: 'Customers using single product, prospects evaluating multiple needs, accounts considering multiple vendors, strategic accounts (platform adoption)',
    engagementTargets: 'Economic buyers (cost efficiency), multiple department heads, executive sponsor, champions across departments',
    expectedOutcome: '40-50% take bundle vs single product, 30-50% higher ACV, platform adoption vs point solution',
    timing: 'During initial sale or expansion; ongoing offer',
  },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const ACTIVITY_MAP = new Map(ACTIVITIES.map((a) => [a.id, a]));

export function getActivity(id: string): ActivityDefinition | undefined {
  return ACTIVITY_MAP.get(id);
}

export function getActivitiesByCategory(
  category: ActivityCategory,
): ActivityDefinition[] {
  return ACTIVITIES.filter((a) => a.category === category);
}

export const CATEGORY_LABELS: Record<ActivityCategory, string> = {
  product: 'Product & Platform',
  event: 'Events & Experiences',
  content_asset: 'Content & Assets',
  gift_touch: 'Gifts & Personal Touches',
  customer_program: 'Customer Programs',
  deal_play: 'Deal Plays & Motions',
};
