'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

type Props = {
  companyId: string;
};

export function AccountMessagingNotification({ companyId }: Props) {
  const [show, setShow] = useState(false);
  const router = useRouter();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const wasGenerated = sessionStorage.getItem('accountMessagingAutoGenerated');
      if (wasGenerated === 'true') {
        setShow(true);
        sessionStorage.removeItem('accountMessagingAutoGenerated');
        // Auto-hide after 10 seconds
        const timer = setTimeout(() => setShow(false), 10000);
        return () => clearTimeout(timer);
      }
    }
  }, []);

  if (!show) return null;

  return (
    <div className="mb-4 p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg">
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <h3 className="text-sm font-semibold text-green-900 dark:text-green-100 mb-1">
            ✓ Account Messaging Auto-Generated
          </h3>
          <p className="text-sm text-green-800 dark:text-green-200">
            Account Messaging has been automatically generated from your research data and your company data.
            You can review and customize it in the Messaging tab.
          </p>
        </div>
        <div className="flex items-center gap-2 ml-4">
          <Link href={`/dashboard/companies/${companyId}?tab=messaging`}>
            <Button size="sm" className="bg-green-600 hover:bg-green-700 text-white dark:bg-green-500 dark:hover:bg-green-600">
              Review Messaging
            </Button>
          </Link>
          <button
            onClick={() => setShow(false)}
            className="text-green-600 dark:text-green-400 hover:text-green-800 dark:hover:text-green-200"
          >
            ✕
          </button>
        </div>
      </div>
    </div>
  );
}
