'use client';

import { useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import type { CompanyResearchData } from '@/lib/research/company-research-schema';

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  companyId: string;
  companyName: string;
  researchData: unknown;
};

export function ResearchReviewModal({
  open,
  onOpenChange,
  companyId,
  companyName,
  researchData,
}: Props) {
  const router = useRouter();
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Parse and validate research data
  const data = researchData as CompanyResearchData;
  if (!data || !data.companyBasics || !data.whatTheyDo || !data.microSegments) {
    return (
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="max-w-4xl bg-white dark:bg-zinc-800">
          <DialogHeader>
            <DialogTitle>Error</DialogTitle>
          </DialogHeader>
          <p className="text-red-600 dark:text-red-400">Invalid research data received.</p>
          <DialogFooter>
            <Button variant="outline" onClick={() => onOpenChange(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    );
  }

  const [companyBasics, setCompanyBasics] = useState(data.companyBasics);
  const [whatTheyDo, setWhatTheyDo] = useState(data.whatTheyDo);
  const [microSegments, setMicroSegments] = useState(data.microSegments);

  const handleSave = useCallback(async () => {
    setSaving(true);
    setError(null);
    try {
      const payload = {
        companyBasics,
        whatTheyDo,
        nvidiaProductFit: data.nvidiaProductFit,
        microSegments,
      };
      const res = await fetch(`/api/companies/${companyId}/apply-research`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const result = await res.json();
      if (!res.ok) {
        throw new Error(result.error || 'Failed to apply research');
      }
      
      // Show success message if Account Messaging was auto-generated
      if (result.messagingGenerated) {
        // Store message in sessionStorage to show after refresh
        if (typeof window !== 'undefined') {
          sessionStorage.setItem('accountMessagingAutoGenerated', 'true');
        }
      }
      
      // Close modal first, then refresh
      onOpenChange(false);
      // Small delay to ensure modal closes smoothly before refresh
      setTimeout(() => {
        router.refresh();
      }, 100);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Save failed');
    } finally {
      setSaving(false);
    }
  }, [companyId, companyBasics, whatTheyDo, microSegments, data.nvidiaProductFit, router, onOpenChange]);

  const updateInitiative = (index: number, value: string) => {
    const updated = [...whatTheyDo.keyInitiatives];
    updated[index] = value;
    setWhatTheyDo({ ...whatTheyDo, keyInitiatives: updated });
  };

  const addInitiative = () => {
    setWhatTheyDo({
      ...whatTheyDo,
      keyInitiatives: [...whatTheyDo.keyInitiatives, ''],
    });
  };

  const removeInitiative = (index: number) => {
    setWhatTheyDo({
      ...whatTheyDo,
      keyInitiatives: whatTheyDo.keyInitiatives.filter((_, i) => i !== index),
    });
  };

  const updateSegmentRole = (
    segmentIndex: number,
    roleType: 'economicBuyer' | 'technicalEvaluator' | 'champion' | 'influencer',
    roleIndex: number,
    value: string
  ) => {
    const updated = [...microSegments];
    const roles = { ...updated[segmentIndex].roles };
    const roleArray = [...roles[roleType]];
    roleArray[roleIndex] = value;
    roles[roleType] = roleArray;
    updated[segmentIndex] = { ...updated[segmentIndex], roles };
    setMicroSegments(updated);
  };

  const addSegmentRole = (
    segmentIndex: number,
    roleType: 'economicBuyer' | 'technicalEvaluator' | 'champion' | 'influencer'
  ) => {
    const updated = [...microSegments];
    const roles = { ...updated[segmentIndex].roles };
    roles[roleType] = [...roles[roleType], ''];
    updated[segmentIndex] = { ...updated[segmentIndex], roles };
    setMicroSegments(updated);
  };

  const removeSegmentRole = (
    segmentIndex: number,
    roleType: 'economicBuyer' | 'technicalEvaluator' | 'champion' | 'influencer',
    roleIndex: number
  ) => {
    const updated = [...microSegments];
    const roles = { ...updated[segmentIndex].roles };
    roles[roleType] = roles[roleType].filter((_, i) => i !== roleIndex);
    updated[segmentIndex] = { ...updated[segmentIndex], roles };
    setMicroSegments(updated);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto bg-white dark:bg-zinc-800">
        <DialogHeader>
          <DialogTitle>Account Profile - Review and Edit</DialogTitle>
          <p className="text-sm text-gray-600 dark:text-gray-300 mt-1">
            Review and edit. This information helps AI write better outreach.
          </p>
        </DialogHeader>

        <div className="space-y-6">
          {error && (
            <div className="p-3 rounded text-sm bg-red-50 dark:bg-red-900/20 text-red-800 dark:text-red-200">
              {error}
            </div>
          )}

          {/* Company Basics */}
          <section className="border border-gray-200 dark:border-zinc-700 rounded-lg p-4 bg-white dark:bg-zinc-800">
            <div className="flex justify-between items-center mb-3">
              <h2 className="font-semibold text-gray-900 dark:text-gray-100">Company Basics</h2>
              <span className="text-xs text-green-600 dark:text-green-400">✅ AI Generated</span>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                  Company Name
                </label>
                <Input
                  value={companyBasics.name}
                  onChange={(e) => setCompanyBasics({ ...companyBasics, name: e.target.value })}
                  className="bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                  Website
                </label>
                <Input
                  value={companyBasics.website || ''}
                  onChange={(e) => setCompanyBasics({ ...companyBasics, website: e.target.value })}
                  className="bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                  Industry
                </label>
                <Input
                  value={companyBasics.industry || ''}
                  onChange={(e) => setCompanyBasics({ ...companyBasics, industry: e.target.value })}
                  className="bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                  Employees
                </label>
                <Input
                  value={companyBasics.employees || ''}
                  onChange={(e) => setCompanyBasics({ ...companyBasics, employees: e.target.value })}
                  placeholder="e.g., ~167,000"
                  className="bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                  Headquarters
                </label>
                <Input
                  value={companyBasics.headquarters || ''}
                  onChange={(e) => setCompanyBasics({ ...companyBasics, headquarters: e.target.value })}
                  placeholder="e.g., Detroit, Michigan"
                  className="bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                  Revenue
                </label>
                <Input
                  value={companyBasics.revenue || ''}
                  onChange={(e) => setCompanyBasics({ ...companyBasics, revenue: e.target.value })}
                  placeholder="e.g., $171.8B (2024)"
                  className="bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                />
              </div>
            </div>
          </section>

          {/* What They Do */}
          <section className="border border-gray-200 dark:border-zinc-700 rounded-lg p-4 bg-white dark:bg-zinc-800">
            <div className="flex justify-between items-center mb-3">
              <h2 className="font-semibold text-gray-900 dark:text-gray-100">What They Do</h2>
              <span className="text-xs text-green-600 dark:text-green-400">✅ AI Generated</span>
            </div>
            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                Summary
              </label>
              <Textarea
                value={whatTheyDo.summary}
                onChange={(e) => setWhatTheyDo({ ...whatTheyDo, summary: e.target.value })}
                rows={4}
                className="bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-2">
                Key Initiatives
              </label>
              {whatTheyDo.keyInitiatives.map((initiative, i) => (
                <div key={i} className="flex gap-2 mb-2">
                  <Input
                    value={initiative}
                    onChange={(e) => updateInitiative(i, e.target.value)}
                    placeholder="e.g., $35B investment in EVs and AVs through 2025"
                    className="flex-1 bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                  />
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => removeInitiative(i)}
                  >
                    Remove
                  </Button>
                </div>
              ))}
              <Button type="button" variant="outline" size="sm" onClick={addInitiative}>
                + Add Initiative
              </Button>
            </div>
          </section>

          {/* Product Fit (Read-only) */}
          {data.nvidiaProductFit.length > 0 && (
            <section className="border border-gray-200 dark:border-zinc-700 rounded-lg p-4 bg-gray-50 dark:bg-zinc-800/50">
              <h2 className="font-semibold text-gray-900 dark:text-gray-100 mb-3">
                How They Could Use Your Products
              </h2>
              <div className="space-y-3">
                {data.nvidiaProductFit.map((fit, i) => (
                  <div key={i} className="border-l-2 border-blue-500 pl-3">
                    <h3 className="font-medium text-gray-900 dark:text-gray-100">{fit.product}</h3>
                    <p className="text-sm text-gray-600 dark:text-gray-300 mt-1">{fit.useCase}</p>
                    <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">{fit.whyRelevant}</p>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* Micro-Segments */}
          <section className="border border-gray-200 dark:border-zinc-700 rounded-lg p-4 bg-white dark:bg-zinc-800">
            <div className="flex justify-between items-center mb-3">
              <h2 className="font-semibold text-gray-900 dark:text-gray-100">Micro-Segments</h2>
              <span className="text-xs text-green-600 dark:text-green-400">✅ AI Generated</span>
            </div>
            <p className="text-sm text-gray-600 dark:text-gray-300 mb-4">
              Who at {companyName} would buy these products?
            </p>
            <div className="space-y-4">
              {microSegments.map((segment, segIndex) => (
                <div
                  key={segIndex}
                  className="border border-gray-200 dark:border-zinc-600 rounded-lg p-4 bg-gray-50 dark:bg-zinc-700/50"
                >
                  <div className="mb-3">
                    <h3 className="font-semibold text-gray-900 dark:text-gray-100">{segment.name}</h3>
                    {segment.departmentType && (
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Department Type: {segment.departmentType}
                      </p>
                    )}
                  </div>
                  <div className="mb-3">
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                      Use Case
                    </label>
                    <Textarea
                      value={segment.useCase}
                      onChange={(e) => {
                        const updated = [...microSegments];
                        updated[segIndex] = { ...updated[segIndex], useCase: e.target.value };
                        setMicroSegments(updated);
                      }}
                      rows={2}
                      className="bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                    />
                  </div>
                  <div className="mb-3">
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                      Products
                    </label>
                    <p className="text-sm text-gray-600 dark:text-gray-300">
                      {segment.products.join(', ')}
                    </p>
                  </div>
                  {segment.estimatedOpportunity && (
                    <div className="mb-3">
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                        Estimated Opportunity
                      </label>
                      <Input
                        value={segment.estimatedOpportunity}
                        onChange={(e) => {
                          const updated = [...microSegments];
                          updated[segIndex] = {
                            ...updated[segIndex],
                            estimatedOpportunity: e.target.value,
                          };
                          setMicroSegments(updated);
                        }}
                        className="bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                      />
                    </div>
                  )}
                  <div className="space-y-3">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-2">
                        Economic Buyer
                      </label>
                      {segment.roles.economicBuyer.map((title, roleIndex) => (
                        <div key={roleIndex} className="flex gap-2 mb-2">
                          <Input
                            value={title}
                            onChange={(e) =>
                              updateSegmentRole(segIndex, 'economicBuyer', roleIndex, e.target.value)
                            }
                            placeholder="e.g., VP Engineering"
                            className="flex-1 bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                          />
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => removeSegmentRole(segIndex, 'economicBuyer', roleIndex)}
                          >
                            Remove
                          </Button>
                        </div>
                      ))}
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => addSegmentRole(segIndex, 'economicBuyer')}
                      >
                        + Add Title
                      </Button>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-2">
                        Technical Evaluator
                      </label>
                      {segment.roles.technicalEvaluator.map((title, roleIndex) => (
                        <div key={roleIndex} className="flex gap-2 mb-2">
                          <Input
                            value={title}
                            onChange={(e) =>
                              updateSegmentRole(segIndex, 'technicalEvaluator', roleIndex, e.target.value)
                            }
                            placeholder="e.g., Director ML"
                            className="flex-1 bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                          />
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => removeSegmentRole(segIndex, 'technicalEvaluator', roleIndex)}
                          >
                            Remove
                          </Button>
                        </div>
                      ))}
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => addSegmentRole(segIndex, 'technicalEvaluator')}
                      >
                        + Add Title
                      </Button>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-2">
                        Champion
                      </label>
                      {segment.roles.champion.map((title, roleIndex) => (
                        <div key={roleIndex} className="flex gap-2 mb-2">
                          <Input
                            value={title}
                            onChange={(e) =>
                              updateSegmentRole(segIndex, 'champion', roleIndex, e.target.value)
                            }
                            placeholder="e.g., Senior ML Engineer"
                            className="flex-1 bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                          />
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => removeSegmentRole(segIndex, 'champion', roleIndex)}
                          >
                            Remove
                          </Button>
                        </div>
                      ))}
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => addSegmentRole(segIndex, 'champion')}
                      >
                        + Add Title
                      </Button>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-2">
                        Influencer
                      </label>
                      {segment.roles.influencer.map((title, roleIndex) => (
                        <div key={roleIndex} className="flex gap-2 mb-2">
                          <Input
                            value={title}
                            onChange={(e) =>
                              updateSegmentRole(segIndex, 'influencer', roleIndex, e.target.value)
                            }
                            placeholder="e.g., ML Engineer"
                            className="flex-1 bg-white dark:bg-zinc-700 text-gray-900 dark:text-gray-100"
                          />
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => removeSegmentRole(segIndex, 'influencer', roleIndex)}
                          >
                            Remove
                          </Button>
                        </div>
                      ))}
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => addSegmentRole(segIndex, 'influencer')}
                      >
                        + Add Title
                      </Button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>
            Cancel
          </Button>
          <Button onClick={handleSave} disabled={saving}>
            {saving ? 'Saving...' : 'Save Account'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
